### ISSUE TITLE
Introduce elliptic curve element type trait

### ISSUE THREAD

**Issue by nemothenoone** [NilFoundation/crypto3-algebra#2] opened 2020-07-22 14:49 UTC
Concept introduction along with type traits formalization is required.

**Comment by nkaskov** [comment] 2020-09-06 10:43
Closed by 4eadbad2a746041eeb7a0276bf8fe4acb2a79331

**Comment by nkaskov** [comment] 2020-11-06 11:48
Depends on #1

**Comment by nkaskov** [comment] 2020-11-25 16:30
Duplicate of #32

**Closed by nkaskov** 2020-11-25 16:30 UTC
Labels: enhancement
